# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np
x = (np.ones((5,5))*6).astype(int)
x[1:-1, 1:-1] = 0
print(x)

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
mat = np.asmatrix(np.ones((8,8))*9).astype(int)
mat[::2,::2] =3
mat[1::2,1::2]=3
print(mat)

[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
print(np.empty((4,4)))
print(np.full((4,4),6))

[[1.57279871e-076 4.01459410e-057 8.97195493e-067 1.04811194e+165]
 [1.47763641e+248 1.16096346e-028 7.69165785e+218 1.35617292e+248]
 [9.10796753e+169 3.40859153e-057 4.66164144e-033 1.81788616e+185]
 [4.26416516e-096 6.32299154e+233 6.48224638e+170 5.22411352e+257]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
sample_array = [0, 12, 45.21 ,34, 99.91]
F = np.array(sample_array)
print('Expected OutputValues in Fahrenheit degrees-\n',F)
print('Values in Centigrade degrees-\n',((F-32)*5/9))

Expected OutputValues in Fahrenheit degrees-
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees-
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [5]:
sample_array = [ 1.00000000+0.j,0.70710678+0.70710678j]
sample_np_array = np.array(sample_array)
print("Real part of the array-\n",sample_np_array.real)
print("Imaginary part of the array-\n",sample_np_array.imag)

Real part of the array-
 [1.         0.70710678]
Imaginary part of the array-
 [0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [6]:
array1 = [ 0, 10, 20, 40, 60]
array2 = [0, 40]
np.in1d(array1, array2)

array([ True, False, False,  True, False])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [7]:
array1 = [ 0, 10, 20, 40, 60]
array2 = [10, 30, 40]
np.intersect1d(array1, array2)

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [8]:
sample_array = [10, 10, 20, 20, 30, 30]
np.unique(np.array(sample_array))

array([10, 20, 30])

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [9]:
array1 = [ 0, 10, 20, 40, 60, 80]
array2 = [10, 30, 40, 50, 70]
np_array1 = np.array(array1)
np_array2 = np.array(array2)
np.setxor1d(np_array1, np_array2)

array([ 0, 20, 30, 50, 60, 70, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [10]:
print(np.all([10,20,0,30]))
print(np.all([10,20,30]))

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [11]:
print(np.any([[False,False],[False,False]]))
print(np.any([[True,True],[True,True]]))
print(np.any([10, 20, 0, -50]))
print(np.any([10, 20, -50]))

False
True
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [12]:
sample_array = [1,2,3,4]
print("Repeating 2 times\n",np.tile(np.array(sample_array),2))
print("Repeating 3 times\n",np.tile(np.array(sample_array),3))


Repeating 2 times
 [1 2 3 4 1 2 3 4]
Repeating 3 times
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [13]:
sample_array = [1,2,3,4,5,6]
print("Maximum values : ", np.argmax(sample_array))
print("Minimum values : ", np.argmin(sample_array))

Maximum values :  5
Minimum values :  0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [14]:
array1 = [1,2]
array2 = [4,5]

print('a>b :',np.greater(array1,array2))
print('a>=b :',np.greater_equal(array1, array2))
print('a<b :', np.less(array1, array2))
print('a<=b : ',np.less_equal(array1, array2))

a>b : [False False]
a>=b : [False False]
a<b : [ True  True]
a<=b :  [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [15]:
a = np.array([[4,6],[2,1]])
print('Expected OutputOriginal array:\n',a)

x= np.sort(a,axis=0)
print('Sort along the first axis:\n',x)

y = np.sort(x,axis=1)
print('Sort along the last axis:\n',y)

Expected OutputOriginal array:
 [[4 6]
 [2 1]]
Sort along the first axis:
 [[2 1]
 [4 6]]
Sort along the last axis:
 [[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [16]:
first_names = ('Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery')
last_names = ('Battle', 'Brien', 'Plotner', 'Stahl', 'Woolum')
ind = np.lexsort((first_names, last_names))
print(ind)

[0 1 2 3 4]


In [17]:
[last_names[i]+" "+first_names[i] for i in ind]

['Battle Betsey',
 'Brien Shelley',
 'Plotner Lanell',
 'Stahl Genesis',
 'Woolum Margery']

Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [18]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [19]:
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))


128 bytes


## Great Job!